### ISSUE TITLE
go-eldoc.el Error: Unrecognized keyword godef-jump

### ISSUE THREAD

**Issue by suntong001** [syohex/emacs-go-eldoc#27]
While installing go-eldoc from elpa, I got the following:

	Compiling no file at Sun Feb 22 15:02:11 2015
	Leaving directory `/home/tong/.emacs.d/elpa/go-eldoc-20141218.2036'
	
	Compiling file /home/tong/.emacs.d/elpa/go-eldoc-20141218.2036/go-eldoc.el at Sun Feb 22 15:02:11 2015
	Entering directory `/home/tong/.emacs.d/elpa/go-eldoc-20141218.2036/'
	go-eldoc.el:37:1:Error: Unrecognized keyword: (bind-key M-. (quote godef-jump) go-mode-map)

and I also get it whenever I open a .go file. 

How can I fix it? 

Thanks

**Comment by syohex** [comment]
Thanks for report.

Which emacs version do you use ?
I cannot reproduce this issue with Emacs 24.3, 24.4, development version.

> go-eldoc.el:37:1:Error: Unrecognized keyword: (bind-key M-. (quote godef-jump) go-mode-map)

This configuration is in `go-mode.el`, not `go-eldoc.el`.
So please retry to install after removing `go-mode` and `go-eldoc`.

**Comment by suntong001** [comment]
On Sun, Feb 22, 2015 at 5:44 PM, Syohei YOSHIDA wrote:

> I cannot reproduce this issue with Emacs 24.3, 24.4, development version.
>
> Ops, should have thought about that.

This configuration is in go-mode.el, not go-eldoc.el.


Oh, ok. I'll see what I can do...

Sorry to have troubled you.

**Comment by syohex** [comment]
Do you resolve this issue by reinstalling ?
