### ISSUE TITLE
Make path to gocode configurable

### ISSUE THREAD

**Issue by avsej** [syohex/emacs-go-eldoc#36]

**Comment by syohex** [comment]
Why do you think so ?

**Comment by avsej** [comment]
Because it just run gocode here
https://github.com/syohex/emacs-go-eldoc/blob/51d24bb59115ef2e1addfd289e9b6ec6470185f4/go-eldoc.el#L149
Would be nice to have it configurable if I installed binary somewhere locally.

**Comment by syohex** [comment]
I fixed at #37. You can set gocode path via `go-eldoc-gocode`. However I think it is better to set PATH environment variable correctly than using this variable.
