### ISSUE TITLE
 Large amount of *go-eldoc* buffers when go-eldoc--invoke-autocomplete has an error

### ISSUE THREAD

**Issue by bmag** [syohex/emacs-go-eldoc#47]
In [`go-eldoc--invoke-autocomplete`](https://github.com/syohex/emacs-go-eldoc/blob/master/go-eldoc.el#L162), if `call-process-region` encounters an  error then the temporary `*go-eldoc*` buffer isn't killed, resulting in many `*go-eldoc*` temporary buffers accumulating in the background. It seems that using `with-temp-buffer` instead of `generate-new-buffer` or `condition-case` instead of `prog2` (and suitable refactoring) should fix this.

Original report: https://github.com/syl20bnr/spacemacs/issues/7979
Related: https://github.com/nsf/gocode/issues/435

**Comment by syohex** [comment]
I have fixed at #48.  Please check it.

**Comment by bmag** [comment]
Thank you
